import type { Amulet } from './types';

export const amulets: Amulet[] = [
  {
    id: '1',
    name: 'ดวงตาแห่งฮอรัส',
    description: 'สัญลักษณ์อียิปต์โบราณแห่งการปกป้อง, อำนาจของราชวงศ์, และสุขภาพที่ดี ดวงตาเป็นตัวแทนของเทพีวัดเจต',
    imageUrls: ['https://placehold.co/600x600.png', 'https://placehold.co/600x400.png', 'https://placehold.co/400x600.png'],
    dataAiHint: 'egyptian amulet',
    history: 'ดวงตาแห่งฮอรัสถูกใช้เป็นเครื่องรางป้องกันและเชื่อว่ามีพลังในการรักษา มักถูกสวมใส่โดยผู้มีชีวิตและรวมอยู่ในการห่อศพของผู้ตาย',
    worshipCount: 1245,
    material: 'ไพฑูรย์',
    userId: 'user-123',
    userName: 'นักสะสมโบราณ',
    auctionType: 'fixed',
    fixedPrice: 7500,
    currentPrice: 7500,
    auctionEndTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    name: 'เวกวิเซียร์ของนอร์ส',
    description: 'สัญลักษณ์เวทมนตร์ของไอซ์แลนด์ที่มีจุดประสงค์เพื่อช่วยให้ผู้ถือหาทางผ่านสภาพอากาศที่เลวร้ายได้ สัญลักษณ์นี้ได้รับการยืนยันในต้นฉบับ Huld',
    imageUrls: ['https://placehold.co/600x600.png'],
    dataAiHint: 'viking compass',
    history: 'แม้ว่ามักจะเกี่ยวข้องกับชาวไวกิ้ง แต่สัญลักษณ์เวกวิเซียร์ถูกบันทึกไว้ในตำราเวทมนตร์ของไอซ์แลนด์จากศตวรรษที่ 19 ซึ่งเป็นเวลานานหลังจากยุคไวกิ้ง เป็นสัญลักษณ์ของการนำทางและการป้องกัน',
    worshipCount: 987,
    material: 'บรอนซ์',
    userId: 'user-456',
    userName: 'นักรบไวกิ้ง',
    auctionType: 'up-bid',
    startPrice: 3000,
    currentPrice: 4500,
    minBidIncrement: 250,
    auctionStartTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    auctionEndTime: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    name: 'มือฮัมซา',
    description: 'เครื่องรางรูปฝ่ามือที่ได้รับความนิยมทั่วตะวันออกกลางและแอฟริกาเหนือ เป็นสัญลักษณ์แห่งการป้องกัน นำมาซึ่งความสุข โชคลาภ สุขภาพ และโชคดี',
    imageUrls: ['https://placehold.co/600x600.png', 'https://placehold.co/600x400.png'],
    dataAiHint: 'protective hand',
    model_3d_url: 'https://example.com/hamsa-hand-3d-model',
    history: 'เชื่อกันว่ามือฮัมซาช่วยป้องกัน "ดวงตาปีศาจ" ถูกสวมใส่เป็นเครื่องประดับและจัดแสดงในบ้าน สัญลักษณ์นี้มีมาก่อนทั้งศาสนายิวและศาสนาอิสลาม',
    worshipCount: 2301,
    material: 'เงินและเทอร์ควอยซ์',
    userId: 'user-789',
    userName: 'ผู้พิทักษ์สันติ',
    auctionType: 'up-bid',
    startPrice: 5000,
    currentPrice: 6250,
    minBidIncrement: 250,
    auctionStartTime: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    auctionEndTime: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    name: 'ปมเซลติก',
    description: 'เป็นตัวแทนของความเชื่อมโยงของชีวิตและนิรันดร ปมเซลติกเป็นสัญลักษณ์ของความศรัทธา ความรัก และวงจรที่ไม่สิ้นสุดของชีวิต ความตาย และการเกิดใหม่',
    imageUrls: ['https://placehold.co/600x600.png'],
    dataAiHint: 'celtic knot',
    history: 'งานปมเซลติกถูกค้นพบในงานศิลปะย้อนหลังไปถึงจักรวรรดิโรมัน รูปแบบที่ซับซ้อนเหล่านี้ถูกใช้โดยพระในต้นฉบับคริสเตียนยุคแรกเช่น Book of Kells',
    worshipCount: 850,
    material: 'ไม้',
    userId: 'user-101',
    userName: 'นักปราชญ์พเนจร',
    auctionType: 'fixed',
    fixedPrice: 3200,
    currentPrice: 3200,
    auctionEndTime: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    name: 'อังค์',
    description: 'อังค์เป็นสัญลักษณ์อักษรอียิปต์โบราณที่ใช้บ่อยที่สุดในการเขียนและในศิลปะอียิปต์เพื่อแทนคำว่า "ชีวิต"',
    imageUrls: ['https://placehold.co/600x600.png'],
    dataAiHint: 'key life',
    history: 'มักถูกเรียกว่า "กุญแจแห่งชีวิต" อังค์ถูกถือโดยเทพเจ้าและฟาโรห์ เป็นสัญลักษณ์ของชีวิตนิรันดร์และมักถูกวางไว้ในสุสานเพื่อให้แน่ใจว่าผู้ตายจะผ่านไปยังชีวิตหลังความตาย',
    worshipCount: 1532,
    material: 'ทองคำ',
    userId: 'user-123',
    userName: 'นักสะสมโบราณ',
    auctionType: 'up-bid',
    startPrice: 15000,
    currentPrice: 18500,
    minBidIncrement: 500,
    auctionStartTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    auctionEndTime: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    name: 'จักจั่นหยก',
    description: 'ในวัฒนธรรมจีน จักจั่นเป็นสัญลักษณ์ของการเกิดใหม่และความเป็นอมตะ เชื่อว่าหยกมีคุณสมบัติในการป้องกันและส่งเสริมอายุยืน',
    imageUrls: ['https://placehold.co/600x600.png'],
    dataAiHint: 'jade insect',
    history: 'จักจั่นหยกถูกวางไว้ในปากของผู้ตายในสมัยราชวงศ์ฮั่นเพื่อให้แน่ใจว่าจะฟื้นคืนชีพและมีชีวิตนิรันดร์ในแดนสุขาวดี',
    worshipCount: 678,
    material: 'หยก',
    userId: 'user-112',
    userName: 'ผู้สืบสานตำนาน',
    auctionType: 'fixed',
    fixedPrice: 9900,
    currentPrice: 9900,
    auctionEndTime: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '7',
    name: 'กอร์โกเนียน',
    description: 'เครื่องรางกันภัยของกรีกโบราณที่แสดงศีรษะของกอร์กอน ที่มีชื่อเสียงที่สุดคือเมดูซ่า ใช้เพื่อปัดเป่าความชั่วร้าย',
    imageUrls: ['https://placehold.co/600x600.png', 'https://placehold.co/400x400.png'],
    dataAiHint: 'medusa head',
    history: 'กอร์โกเนียนเป็นสัญลักษณ์ป้องกันที่ได้รับความนิยมในกรีกโบราณ ปรากฏบนโล่, วิหาร, และเครื่องปั้นดินเผาเพื่อปัดเป่าวิญญาณชั่วร้ายและดวงตาปีศาจ',
    worshipCount: 431,
    material: 'ดินเผา',
    userId: 'user-456',
    userName: 'นักรบไวกิ้ง',
    auctionType: 'fixed',
    fixedPrice: 2500,
    currentPrice: 2500,
    auctionEndTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '8',
    name: 'แมลงสคารับ',
    description: 'สัญลักษณ์ของการฟื้นฟูและการเกิดใหม่ในอียิปต์โบราณ แมลงสคารับเป็นตัวแทนของดวงอาทิตย์ยามเช้า, เคปริ, ผู้ซึ่งกลิ้งดวงอาทิตย์ข้ามท้องฟ้าในแต่ละวัน',
    imageUrls: ['https://placehold.co/600x600.png'],
    dataAiHint: 'egyptian beetle',
    history: 'เครื่องรางสคารับเป็นที่แพร่หลายอย่างมากในอียิปต์โบราณและใช้สำหรับการป้องกัน, เป็นตราประทับ, และในพิธีกรรมงานศพเพื่อให้แน่ใจว่าหัวใจจะไม่เป็นพยานปรักปรำผู้ตาย',
    worshipCount: 1102,
    material: 'สตีไทต์',
    userId: 'user-123',
    userName: 'นักสะสมโบราณ',
    auctionType: 'up-bid',
    startPrice: 4000,
    currentPrice: 4000,
    minBidIncrement: 200,
    auctionStartTime: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    auctionEndTime: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '9',
    name: 'ลูกปัดโบราณ',
    description: 'ลูกปัดแก้วโบราณจากยุคทวารวดี เชื่อว่านำโชคและป้องกันภัย',
    imageUrls: ['https://placehold.co/600x600.png'],
    dataAiHint: 'ancient bead',
    history: 'ลูกปัดเหล่านี้เป็นส่วนหนึ่งของเครือข่ายการค้าทางทะเลโบราณที่เชื่อมต่อเอเชียตะวันออกเฉียงใต้กับอินเดียและตะวันออกกลาง',
    worshipCount: 350,
    material: 'แก้ว',
    userId: 'user-101',
    userName: 'นักปราชญ์พเนจร',
    auctionType: 'down-bid',
    startPrice: 8000,
    currentPrice: 8000,
    auctionStartTime: new Date(Date.now()).toISOString(),
    auctionEndTime: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
